crsh:
  Language:
    Default:
      '1': en-us
    DefaultList: '{CS_BaseDir}\core\langlist.json'
    LangFormat: json
    ListFormat: json
  Packages:
    AllowedFileTypes:
      Cmdlets:
        INTERNAL_PYTHON:
        - .py
        SYSTEM_EXECUTABLE:
        - win@.exe
        - lnx@MIME_EXECUTABLE
      Packages:
        Legacy:
        - package
        - pack
        - cspack
        Modulo:
        - mpackage
        - mpack
        - csmpack
    test:
      test: hi
    test2:
      test: hi
crsh_debugger:
  Mode: limited
