crsh:
  Language:
    Default:
      '1': en-us
    DefaultList: '{CS_BaseDir}\core\langlist.json'
    LangFormat: json
    ListFormat: json
  Packages:
    AllowedFileTypes:
      Cmdlets:
        Legacy:
        - .py
        Modulo:
        - .py
crsh_debugger:
  Mode: 'limited'
