crsh:
  Parse:
    Text:
      Webcolors: true
  Execution:
    HandleCmdletError: true
    PrintCmdletDebug: true
    SplitByNewline: true
    SafelyHandleExit: true
    OnlyAllowCmdlets: false
    PrintComments: true
  Formats:
    DefaultEncoding: utf-8
  Language:
    Loaded:
      '1': en-us
      '0': sv-se
    _choices: []
    DefaultList: '{CS_BaseDir}\assets\langlist.json'
    ListFormat: json
    LangFormat: json
    LoadSameSuffixedLangs: true
  Packages:
    Options:
      LoadInFileHeader: true
    AllowedFileTypes:
      Cmdlets:
        INTERNAL_PYTHON:
        - py
        PLATFORM_EXECUTABLE:
        - win@exe
        - win@cmd
        - win@bat
        - lnx;mac@MIME_EXECUTABLE
      Packages:
        Modulo:
        - mpackage
        - mpack
        - csmpack
        Legacy:
        - package
        - pack
        - cspack
      CmdletFiles:
        Conf:
        - cfg
        - config
        - conf
        Pack:
        - json
        - cfg
        - conf
        - config
    Readers:
      ReaderFile: '{CS_BaseDir}\assets\readerfiles.json'
    Formatting:
      Palettes:
        Selected: null
        _choices: []
      Mappings:
        Selected: null
        _choices: []
  Console:
    DefPrefix: '> '
    DefTitle: Crosshell Modulo
    PrefixEnabled: true
    PrefixShowDir: false
    DynamicPrefixes: true
    RestrictDynPrefixes: false
    StripAnsi: false
    FormatOutMode: format
    ClearOnStart: false
    Welcome:
      ShowOnStart: true
      ShowVersionNotice: true
      ShowProfile: true
    VerboseStart: true
  SmartInput:
    Enabled: true
    TabComplete: true
    History: true
    Highlight: true
    ShowToolbar: true
    MultiLine: false
    MouseSupport: false
    LineWrap: true
    CursorChar: BLINKING_BEAM
    HistorySuggest: true
    HistoryType: File
    Styling:
      Enabled: true
      Options:
        bottom-toolbar: fg:#181818 bg:#107c41
        completion-menu: 'bg:#151515 #eeeeee'
        completion-menu.completion.current: bg:#2f2f2f
      Completions:
        cmd: fg:#b3b4b6
        arg: fg:#5555ff
        custom: fg:magenta
      Inject: true
    HistoryFile: '{CS_BaseDir}\assets\.history'
    Completions:
      IncludeStandards: true
      IncludeArgs: true
      IncludeCmdCustoms: true
      HideByContext: true
  Modules:
    Files:
      console-py:
        selection: null
        _choices:
        - test
      inpparse-py:
        selection: null
        _choices: null
      exec-py:
        selection: null
        _choices: null
  Version:
    VerFile: '{CS_CoreDir}\version.yaml'
    FileFormatVer: '1'
  CGTS:
    ANSI_Hex_Palette:
      '30': f#000000
      '31': f#FF0000
      '32': f#00FF00
      '33': f#FFFF00
      '34': f#0000FF
      '35': f#FF00FF
      '36': f#00FFFF
      '37': f#FFFFFF
      '90': f#555555
      '91': f#FF5555
      '92': f#55FF55
      '93': f#FFFF55
      '94': f#5555FF
      '95': f#FF55FF
      '96': f#55FFFF
      '97': f#FFFFFF
      '40': b#000000
      '41': b#FF0000
      '42': b#00FF00
      '43': b#FFFF00
      '44': b#0000FF
      '45': b#FF00FF
      '46': b#00FFFF
      '47': b#FFFFFF
      '100': b#555555
      '101': b#FF5555
      '102': b#55FF55
      '103': b#FFFF55
      '104': b#5555FF
      '105': b#FF55FF
      '106': b#55FFFF
      '107': b#FFFFFF
    CustomMappings: {}
crsh_debugger:
  Scope: error
  Execution:
    AllowRunAsInternal: true
