crsh:
  Formats:
    DefaultEncoding: utf-8
  Language:
    Default:
      '1': en-us
    DefaultList: '{CS_BaseDir}\assets\langlist.json'
    LangFormat: json
    ListFormat: json
  Packages:
    AllowedFileTypes:
      CmdletFiles:
        Conf:
        - cfg
        - config
        - conf
        Pack:
        - json
        - cfg
        - conf
        - config
      Cmdlets:
        INTERNAL_PYTHON:
        - py
        PLATFORM_EXECUTABLE:
        - win@exe
        - win@cmd
        - win@bat
        - lnx;mac@MIME_EXECUTABLE
      Packages:
        Legacy:
        - package
        - pack
        - cspack
        Modulo:
        - mpackage
        - mpack
        - csmpack
    Readers:
      ReaderFile: '{CS_BaseDir}\assets\readerfiles.json'
crsh_debugger:
  Mode: limited
