crsh:
  Console:
    DefPrefix: '> '
    DefTitle: Crosshell Modulo
    DynamicPrefixes: true
    FormatOutMode: format
    PrefixEnabled: true
    PrefixShowDir: true
    RestrictDynPrefixes: false
    StripAnsi: false
  Execution:
    CatchSystemExit: true
    HandleCmdletError: true
    OnlyAllowCmdlets: true
    PrintCmdletDebug: true
    SafelyHandleExit: true
    SplitByNewline: false
  Formats:
    DefaultEncoding: utf-8
  Language:
    Default:
      '1': en-us
    DefaultList: '{CS_BaseDir}/assets/langlist.json'
    LangFormat: json
    ListFormat: json
  Modules:
    Files:
      console-py:
        _choices:
        - test
        selection: null
      exec-py:
        _choices: null
        selection: null
      inpparse-py:
        _choices: null
        selection: null
    Readers:
      ReaderFile: '{CS_BaseDir}/assets/readerfiles.json'
  Packages:
    AllowedFileTypes:
      CmdletFiles:
        Conf:
        - cfg
        - config
        - conf
        Pack:
        - json
        - cfg
        - conf
        - config
      Cmdlets:
        INTERNAL_PYTHON:
        - py
        PLATFORM_EXECUTABLE:
        - win@exe
        - win@cmd
        - win@bat
        - lnx;mac@MIME_EXECUTABLE
        html:
        - html
      Packages:
        Legacy:
        - package
        - pack
        - cspack
        Modulo:
        - mpackage
        - mpack
        - csmpack
    Options:
      LoadInFileHeader: true
    Readers:
      ReaderFile: '{CS_BaseDir}/assets/readerfiles.json'
  Parse:
    Text:
      Webcolors: true
crsh_debugger:
  Execution:
    AllowRunAsInternal: true
  Scope: error
